version : '3'

# To start:     $ docker-compose up -d
# To tear-down: $ docker-compose down --volumes

services:
  postgres:
    container_name: test_pgsql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root@123}
      PGDATA: /data/postgres
    volumes:
       - v_test_pgsql:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: test_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tranphuquy19@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root@123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - v_test_pgadmin:/root/.pgadmin
    ports:
      - "5433:80"
    restart: unless-stopped

  mongodb:
      image: mongo
      volumes:
          - v_test_mongo:/data/db
      container_name: test_mongo
      environment:
          - MONGO_INITDB_DATABASE=test
      ports:
          - 27017-27019:27017-27019

  redis:
      image: redis:alpine
      container_name: test_redis
      ports:
        - 6379:6379
      volumes:
        - v_test_redis:/data

volumes:
  v_test_pgsql: {}
  v_test_pgadmin: {}
  v_test_mongo: {}
  v_test_redis: {}